# Generated by Django 3.0.7 on 2020-07-22 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wanted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30, verbose_name='nome')),
                ('alcunha', models.CharField(max_length=30, verbose_name='alcunha')),
                ('foto', models.FileField(upload_to='fotos', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'wanted',
                'verbose_name_plural': "wanted's",
            },
        ),
    ]
