# Generated by Django 3.0.7 on 2020-07-22 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_want', '0002_wanted_recompensa'),
    ]

    operations = [
        migrations.CreateModel(
            name='bando',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='nome')),
                ('tripulante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_want.wanted')),
            ],
            options={
                'verbose_name': 'bando',
            },
        ),
    ]
