# Generated by Django 3.0.7 on 2020-07-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_want', '0003_bando'),
    ]

    operations = [
        migrations.AddField(
            model_name='bando',
            name='imagem',
            field=models.FileField(default=-1.0, upload_to='jollyRoger', verbose_name='jolly Roger'),
            preserve_default=False,
        ),
    ]
