# Generated by Django 3.0.7 on 2020-08-02 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_want', '0004_bando_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bando',
            name='tripulante',
        ),
        migrations.AddField(
            model_name='wanted',
            name='bando',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_want.bando'),
            preserve_default=False,
        ),
    ]
