# Generated by Django 3.0.7 on 2020-08-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_want', '0006_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='texto',
            name='status',
            field=models.CharField(choices=[['analise', '1'], ['publicado', '2']], default=-1.0, max_length=15),
            preserve_default=False,
        ),
    ]
