# Generated by Django 3.0.7 on 2020-08-02 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_want', '0010_texto_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagem',
            field=models.FileField(null=True, upload_to='fotos'),
        ),
    ]
